version: '{build}'

skip_tags: true

branches:
  only:
    - master

image:
  - Visual Studio 2017
  - macos-mojave

install:
  - ps: $env:SUFFIX = $(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
    
  # the Windows servers use mingw. bash commands are usable on all
  # platforms.
  - uname
  - env
  - npm version
  - node --version
  
  # why is the case not consistent.
  - if test "$CI_MACOS" = "true"; then echo macOS; fi
  - if test "$CI_WINDOWS" = "True"; then echo Windows; fi
  
  # on macOS, select version using nvm.
  - if test "$CI_MACOS" = "true"; then nvm ls; fi
  - if test "$CI_MACOS" = "true"; then nvm use 10; fi

  # on Windows, select version using PowerShell Install-Product.
  - ps: |
      if ($env:CI_WINDOWS -eq $true) {
        # https://www.appveyor.com/docs/lang/nodejs-iojs/
        Install-Product node 10.13
      }
      
  - npm version
  - node --version
  - git submodule init
  - git submodule update
  # - ps: $env:SUFFIX = $(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
  # - ps: $env:RELEASE_NAME = "beeblink-"+$env:SUFFIX
  # - ps: $env:OUTPUT_NAME = "beeblink-"+$env:SUFFIX+"-server-windows.zip"

build_script:
  - ps: cd ./server
  - npm install
  - npm run compile
  - ps: |
      if ($env:CI_WINDOWS -eq $true) {
        ./node_modules/.bin/pkg -t win .
      } elseif ($env:CI_MACOS -eq $true) {
        ./node_modules/.bin/pkg -t macos-x64 .
      }
      
  # - ps: .\node_modules\.bin\pkg -t win .
  # - ps: 7z a ..\%OUTPUT_NAME% .\beeblink-server.exe .\node_modules\@serialport\bindings\build\Release\bindings.node .\node_modules\usb\build\Release\usb_bindings.node
  # - ps: cd ..
  # - ps: 7z a %OUTPUT_NAME% .\volumes

# artifacts:
#   - path: $(OUTPUT_NAME)
#     name: output

# deploy:
#   - release: $(RELEASE_NAME)
#     provider: GitHub
#     auth_token:
#       secure: T5CPAJmNl5j/eAVlQln8WoiFKTDkq2ebT9Y/PbWRbMIa4GFyov+t5QdqlU0O2sY9
#     artifact: output
#     draft: false
#     prerelease: false
#     on:
#       branch: master
